### PR TITLE
Adapt year webapp

### PR DESCRIPTION
**Pull request by JulianRoesner**
# Short Description
We need to update all occurrences of 2020 to 2021. This should do that. I did not change anything in methods or Erica as this should be part of the ticket where we change sending the tax declaration to 2020.

# Changes
- Update the occurrences
- Some reformats of tests that I saw while searching for 2020

# Feedback
- Do you see anything that I missed

# How to review this Pull Request
[Link to Confluence](https://digitalservice4germany.atlassian.net/wiki/spaces/STL/pages/117637157/Development+Process#Approve-or-comment) (internal)

### CODE REVIEW

**Review by frederike-ramin — CHANGES_REQUESTED** [review]
Did you maybe forget to commit the translations.js? (And I'd also suggest changing the stories.)

**Comment by JulianRoesner** [comment]
> Did you maybe forget to commit the translations.js? (And I'd also suggest changing the stories.)

Thanks for the catch

**Review by nfelger — COMMENTED** [review]
Looks good to me.

- What about acceptance tests? Do they also go into the other ticket?
- Some tests in `tests.forms.steps.lotse_multistep_flow_steps.personal_data_steps#TestFamilienstand` and `tests.model.test_form_data#TestShowPersonB` still use 2020. Is that ok?

**Comment by JulianRoesner** [comment]
> What about acceptance tests? Do they also go into the other ticket?
Some tests in tests.forms.steps.lotse_multistep_flow_steps.personal_data_steps#TestFamilienstand and tests.model.test_form_data#TestShowPersonB still use 2020. Is that ok?

Very good aspects. So far, we do not really send a tax declaration for 2021. Therefore, I did not change these. However,  I will have a look after we merged #474.

**Review by nfelger — APPROVED** [review]

**Review by frederike-ramin — APPROVED** [review]
So great. 👍

**Pull request merged**
