### PR TITLE
STL-1791: fix(translations): offer correct error help text for familienstand form

### PR DESCRIPTION
**Pull request by punknoir101**
# Short Description
- text corrections

# Changes
- text corrections for familienstand step

# Feedback
- Are these the correct formulations? Any typos?

# How to review this Pull Request
[Link to Confluence](https://digitalservice4germany.atlassian.net/wiki/spaces/STL/pages/117637157/Development+Process#Approve-or-comment) (internal)

### CODE REVIEW

**Comment by JulianRoesner** [comment]
> Regarding the changes you made, I would:
> 
> Todesdatum --> Sterbedatum, the one you chose sounds pretty hard
> Datum der Trennung --> Datum der Scheidung, we are talking about a legally binding step right?
The error texts are specified [in this ticket](https://steuerlotse.atlassian.net/browse/STL-1413?atlOrigin=eyJpIjoiMzUzNTgzZWZkZDc2NGMzZDlhZGFlYjllZWEyYzM2MzEiLCJwIjoiaiJ9). There is no text for a divorce, so maybe we need to talk with Nadine about that but "Todesdatum" would be correct.

> Geben Sie ein vollständiges Datum ein.. (for both death and divorce)
The same applies here: That would be the specified text for death but for divorce no error text was specified and we maybe need to ask Nadine.

Besides that, it looks good to me. Thanks!

**Review by JulianRoesner — APPROVED** [review]
If the text are fine with Nadine, I think this is good

**Comment by punknoir101** [comment]
> If the text are fine with Nadine, I think this is good

Thanks for the hint with the ticket - I even found the divorce texts, because of asking UX simultaneously.

**Review by VictorDelCampo — APPROVED** [review]
Thanks!

**Pull request merged**
