### PR TITLE
Add skip-to-content link

### PR DESCRIPTION
**Pull request by frederike-ramin**
# Short Description
- Add a link to enable screen reader users to skip directly to content

# Changes
- Add link that is not visible, but becomes visible when in focus
- Converted main <div> into <main> for more explicit use of html
- Removed footer block as it was never used

# Feedback
- Was this what you expected? I am not sure about the look of the link if it's visible. I don't think it matters though.

### CODE REVIEW

**Review by JulianRoesner — COMMENTED** [review]
Thank you.

Unfortunately, I had something slightly different in mind 😬 I am sorry. I guess the specifications were not precise enough. What we discussed was to just put it in the navigation as the first element (above Übersicht). You would not need to hide it outside of the screen then (I know that this is what was recommended in the article and to be honest I also like it).

Maybe let's quickly talk about this?

**Comment by frederike-ramin** [comment]
Update: Nadine is having another look at it.

**Comment by frederike-ramin** [comment]
@JulianRoesner I styled it according to Nadines design: https://www.figma.com/file/8wdB4SGxroQ4hBrO8lbjJ4/Steuerlotse-UI?node-id=2997%3A2562
Do you wanna have another look at it?

**Review by JulianRoesner — APPROVED** [review]
Looks good to me.

**Pull request merged**
