### PR TITLE
Tests for Reactify login failure

### PR DESCRIPTION
**Pull request by frederike-ramin**
# Short Description
- I completely forgot to push the tests I already wrote for #465 

# Changes
- Add functional tests

# Feedback
- Probably none, as you maybe didn't even want them in the other PR? :D (I thought, I'd just push them anyway as I already wrote them^^)

# How to review this Pull Request
[Link to Confluence](https://digitalservice4germany.atlassian.net/wiki/spaces/STL/pages/117637157/Development+Process#Approve-or-comment) (internal)

### CODE REVIEW

**Review by SannyNguyenHung — COMMENTED** [review]
Hey Frede, where are the tests? The changes looking good for me :)

**Comment by frederike-ramin** [comment]
They are in `webapp/client/cypress/integration/loginFailure.spec.js` - I'm so confused...why is GitHub displaying the other stuff as changes?! They should already be on main..

**Comment by frederike-ramin** [comment]
Aha..apparently I had to merge main again. 👍 Thanks for the hint.

**Review by SannyNguyenHung — APPROVED** [review]
Nice! LGTM!

**Pull request merged**
